[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ast = true
extra_output = ["storageLayout", "abi", "evm.methodIdentifiers", "evm.deployedBytecode.object", "devdoc"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.no-cse]
out="no-cse-out"